title: "Unblah"
tagline: "For those (like myself) who often talk too much (or too little) in meetings because they get nervous"
headline: "For those (like myself) who often talk too much (or too little) in meetings because they get nervous"
description: "Unblah is a meeting-buddy who keeps track of how long you're speaking, catches you before you talk too much and helps you develop a better sense of timing."
email: alexis.rondeau@gmail.com
timezone: UTC
baseurl: ""
favicon: 'assets/images/favicon.ico'
author: Alexis Rondeau
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

plugins:
- jekyll-sitemap
- jekyll-seo-tag
