title: "Unblah"
headline: "Learn to say more while talking less"
email: alexis.rondeau@gmail.com
timezone: UTC
baseurl: ""
logo: 'assets/images/unblah-app-icon.png'
favicon: 'assets/images/favicon.ico'
author: Alexis Rondeau
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

plugins:
- jekyll-sitemap
- jekyll-seo-tag
